name: tvOS

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        uses: tayloraswift/swift-device-action/.github/workflows/build.yml@master
        with:
            xcode-scheme: 'swift-bson-Package'
            destination: ${{ github.workflow }}
